services:
  - type: web
    name: el-horno-del-pinguino-landing-page
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_API_BASE_URL
        value: https://horno-product-admin.onrender.com
      - key: PUBLIC_WHATSAPP_NUMBER
        value: "593994808252"
      - key: PUBLIC_INSTAGRAM_HANDLE
        value: elhornodelpinguino
